name: docs

on:
  workflow_dispatch:
  push:

jobs:
  evaluate-label:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.label_step.outputs.version }}
    steps:
      - name: Check label for deployment
        id: label_step
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
              echo "version=latest" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref_type }}" == "tag" ]]; then
              echo "version=stable" >> $GITHUB_OUTPUT
          else
              echo "No deployment for this ref" >&2
              exit 1
          fi
          

  deploy-docs:
    needs: [evaluate-label]
    uses: qiboteam/workflows/.github/workflows/deploy-ghpages-latest-stable.yml@v1
    with:
      python-version: "3.11"
      package-manager: "poetry"
      dependency-path: "**/poetry.lock"
      trigger-label: "${{ needs.evaluate-label.outputs.label }}"
      poetry-extras: --with docs
      project: qiboml
